### ISSUE TITLE
SMS Time Fix doesn't autostart on x10 Mini Pro with CM Gingerbread

### ISSUE THREAD

**Issue by GijsTimmers** [mattprecious/smstimefix#34]
SMS Time Fix works, but it doesn't autostart. Device:

Sony Ericsson x10 Mini Pro
Android 2.3.7
Kernel 2.6.29-nAa-14
Modversion MiniCM7-2.2.1-mimmi

I suspect that this has something to do with the receivers. Please change the receivers. For instance, make it so that SMS Time Fix starts when the phone has connected succesfully with the carrier's phone network.

**Comment by mattprecious** [comment]
Have you moved the app to the SD card? Apps are not able to auto-start when they're installed on the SD card.

**Comment by GijsTimmers** [comment]
Yes. I just changed the location to the internal memory, which fixed the issue. Thanks for your quick reply.

**Comment by mattprecious** [comment]
Great!
